SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT C2.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
    WHERE MONTH(C2.START_DATE) BETWEEN "8" AND "10"
    GROUP BY C2.CAR_ID
    HAVING COUNT(*) >= 5)
GROUP BY CAR_ID, MONTH
HAVING MONTH BETWEEN "8" AND "10"
ORDER BY MONTH, CAR_ID DESC