SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
WHERE C.CAR_ID IN (
    SELECT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE MONTH(H.START_DATE) = "10"
) AND C.CAR_TYPE = "세단"
ORDER BY C.CAR_ID DESC